version: '3'
services:
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=MusiFetch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MusiFetch
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
    networks:
      - db_network
  python:
    build:
      context: ./docker/python
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - db_network
  web:
    build: ./src/site/musifetch
    command: bash -c "python manage.py migrate && python -u manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/site/musifetch:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db_network
networks:
  db_network: